# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Tags
    url: tags/
    weight: 20
  - name: Blog
    url: blog/
    weight: 30
  - name: About Me
    url: about/
    weight: 40
